import type { Document } from '@/types';

export const DEMO_DOCS: Document[] = [
  {
    id: 'demo-1',
    user_id: 'demo',
    title: 'The Great Gatsby',
    file_name: 'gatsby.docx',
    file_type: 'docx',
    storage_path: '',
    parsed_html: '<h1>The Great Gatsby</h1><p>In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since.</p><p>"Whenever you feel like criticizing any one," he told me, "just remember that all the people in this world haven’t had the advantages that you’ve had."</p>',
    word_count: 47094,
    cover_color: '#b5d5e0',
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    scroll_pct: 62,
    last_read: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'demo-2',
    user_id: 'demo',
    title: 'Design Patterns: Elements of Reusable Software',
    file_name: 'design-patterns.pdf',
    file_type: 'pdf',
    storage_path: '',
    parsed_html: null,
    word_count: 120000,
    cover_color: '#d4e0b5',
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    scroll_pct: 28,
    last_read: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'demo-3',
    user_id: 'demo',
    title: 'Atomic Habits',
    file_name: 'atomic-habits.docx',
    file_type: 'docx',
    storage_path: '',
    parsed_html: '<h1>Atomic Habits</h1><h2>The Surprising Power of Atomic Habits</h2><p>The fate of British Cycling changed one day in 2003. The organization, which was the governing body for professional cycling in Great Britain, had recently hired Dave Brailsford as its new performance director.</p><p>Brailsford had been hired to put British Cycling on a new trajectory. What made him different from previous coaches was his relentless commitment to a strategy that he referred to as "the aggregation of marginal gains," which was the philosophy of searching for a tiny margin of improvement in everything you do.</p><p>Brailsford said, "The whole principle came from the idea that if you broke down everything you could think of that goes into riding a bike, and then improve it by 1 percent, you will get a significant increase when you put them all together."</p><blockquote><p>Habits are the compound interest of self-improvement.</p></blockquote><p>It is so easy to overestimate the importance of one defining moment and underestimate the value of making small improvements on a daily basis. Too often, we convince ourselves that massive success requires massive action.</p>',
    word_count: 67000,
    cover_color: '#e0c9b5',
    created_at: new Date(Date.now() - 21 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    scroll_pct: 100,
    last_read: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'demo-4',
    user_id: 'demo',
    title: 'Clean Code',
    file_name: 'clean-code.pdf',
    file_type: 'pdf',
    storage_path: '',
    parsed_html: null,
    word_count: 88000,
    cover_color: '#d5b5e0',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    scroll_pct: 0,
    last_read: undefined,
  },
  {
    id: 'demo-5',
    user_id: 'demo',
    title: 'The Pragmatic Programmer',
    file_name: 'pragmatic-programmer.docx',
    file_type: 'docx',
    storage_path: '',
    parsed_html: '<h1>The Pragmatic Programmer</h1><p>Programming is a craft. At its simplest, it comes down to getting a computer to do what you want it to do (or what your user wants it to do). As a programmer, you are part listener, part advisor, part interpreter, and part dictator. You try to capture elusive requirements and find a way of expressing them so that a mere machine can do them justice.</p>',
    word_count: 95000,
    cover_color: '#b5e0d4',
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
    scroll_pct: 15,
    last_read: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];
